FROM debian:buster

# Install dependencies
RUN apt update && \
    apt install -y curl vim && \
    apt clean && \
    apt clean cache  # Is this needed?

COPY container-install.sh ./
COPY entrypoint.sh ./